apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-world-rc
spec:
  replicas: 2
  selector:
    app: hello-world
  template:
    metadata:
      name: somename
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: d0x2f/http-hello-world:v1.0.0
        ports:
        - containerPort: 30101